PL/Controllers/DepartamentoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class DepartamentoController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = BL.Departamento.GetAll();
            ML.Departamento departamento = new ML.Departamento();

            if (result.Correct)
            {
                departamento.Departamentos = result.Objects;   
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta ";
            }


            return View(departamento);
        }

        [HttpGet]
        public ActionResult Form(int? IdDepartamento)
        {
            ML.Departamento departamento = new ML.Departamento();

            departamento.Area = new ML.Area();

            ML.Result resultArea = BL.Area.GetAll();

            if(IdDepartamento ==null)
            {
                departamento.Area.Areas = resultArea.Objects;
                return View(departamento);
            }
            else
            {
                ML.Result result = BL.Departamento.GetById(IdDepartamento.Value);

                if(result.Correct)
                {
                    departamento = (ML.Departamento)result.Object;
                    departamento.Area.Areas = resultArea.Objects;
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al buscar al departamento";
                }
                return View(departamento);

            }

            
        }

        [HttpPost]
        public ActionResult Form(ML.Departamento departamento)
        {
            if(departamento.IdDepartamento == 0)
            {
                ML.Result result = BL.Departamento.Add(departamento);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
                    
            }
            else
            {
                ML.Result result = BL.Departamento.Update(departamento);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }

            }
            return PartialView("Modal");
        }

        public ActionResult Delete(int IdDepartamento)
        {
            if (IdDepartamento > 0)
            {
                ML.Result result = BL.Departamento.Delete(IdDepartamento);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
                return PartialView("Modal");
        }
    }
}

PL/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;

namespace PL.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IConfiguration _configuration;

        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostingEnvironment;

        public UsuarioController(IConfiguration configuration, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
        {
            _configuration = configuration;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result resultRol = BL.Rol.GetAll();
            ML.Usuario usuario = new ML.Usuario();
            usuario.Rol = new ML.Rol();
            //ML.Result result = BL.Usuario.GetAll(usuario);

            ML.Result result = new ML.Result();

            result.Objects = new List<object>();



            try
            {
                string urlAPI = _configuration["UrlAPI"];

                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(urlAPI);

                    var responseTask = client.GetAsync("Usuario/GetAll");  //equivale al result = Bl.Usuario.GetAll();

                    responseTask.Wait();

                    var resultServicio = responseTask.Result;

                    if(resultServicio.IsSuccessStatusCode) //validamos el estado de la petición
                    {
                        var readTask = resultServicio.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();

                        foreach (var resultItem in readTask.Result.Objects)
                        {
                            ML.Usuario resultItemList = JsonConvert.DeserializeObject<ML.Usuario>(resultItem.ToString());

                            result.Objects.Add(resultItemList);
                        }
                        result.Correct = true;
                        
                    }
                    

                }
            }
            catch(Exception ex)
            {
                result.Correct = false;
                result.Message = ex.Message;
            }
                
           
            if (result.Correct)
            {
              //guardamos la lista de objetos en una lista de usuarios 
               
                usuario.Rol.Roles = resultRol.Objects;
                usuario.Usuarios = result.Objects;

                return View(usuario);
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta ";
                return PartialView("Modal");
            }

            

        }

        [HttpPost]
        public ActionResult GetAll(ML.Usuario usuario)
        {

            ML.Result result = new ML.Result();

           

            result.Objects = new List<object>();


            usuario.Rol = new ML.Rol();
            // ML.Result result = BL.Usuario.GetAll(usuario);try{
            try
            {
                string urlAPI = _configuration["UrlAPI"];
                using (var client = new HttpClient())
                {
                    client.BaseAddress =new  Uri(urlAPI);

                    var responseTask = client.GetAsync("Usuario/GetAll/" + usuario.Nombre + usuario.ApellidoPaterno + usuario.Rol.IdRol);
                    responseTask.Wait();

                    var resultServicio = responseTask.Result;

                    if(resultServicio.IsSuccessStatusCode)
                    {
                        var readTask = resultServicio.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();

                        foreach (var resultItem in readTask.Result.Objects)
                        {
                            ML.Usuario resultItemList = JsonConvert.DeserializeObject<ML.Usuario>(resultItem.ToString());

                            result.Objects.Add(resultItemList);
                        }
                        result.Correct = true;
                    }
                }
            }
            catch(Exception ex)
            {
                result.Correct = false;
                result.Message = ex.Message;
            }

            if (result.Correct)
            {
                usuario.Rol = new ML.Rol();
                ML.Result resultRol = BL.Rol.GetAll();
                usuario.Rol.Roles = resultRol.Objects;
                usuario.Usuarios = result.Objects;   //guardamos la lista de objetos en una lista de usuarios 
                return View(usuario);
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta ";
                return View();
            }



        }

        [HttpGet]
        public ActionResult Form(int? IdUsuario)
        {
            ML.Usuario usuario = new ML.Usuario();
            usuario.Rol = new ML.Rol();
            usuario.Direccion = new ML.Direccion();
            usuario.Direccion.Colonia = new ML.Colonia();
            usuario.Direccion.Colonia.Municipio = new ML.Municipio();
            usuario.Direccion.Colonia.Municipio.Estado = new ML.Estado();
            usuario.Direccion.Colonia.Municipio.Estado.Pais = new ML.Pais();

            ML.Result resultPais = BL.Pais.GetAll();
            ML.Result resultRol = BL.Rol.GetAll();


            if (IdUsuario == null)
            {
                usuario.Rol.Roles = resultRol.Objects;
                usuario.Direccion.Colonia.Municipio.Estado.Pais.Paises = resultPais.Objects;
                return View(usuario);
            }
            else
            {
                //ML.Result result = BL.Usuario.GetById(IdUsuario.Value);

                ML.Result result = new ML.Result();
                try
                {
                    string urlAPI = _configuration["UrlAPI"];

                    using(var client = new HttpClient())
                    {
                        client.BaseAddress = new Uri(urlAPI);

                        var responseTask = client.GetAsync("Usuario/GetById/" + IdUsuario);

                        responseTask.Wait();

                        var resultServicio = responseTask.Result;

                        if (resultServicio.IsSuccessStatusCode)
                        {
                            var readTask = resultServicio.Content.ReadAsAsync<ML.Result>();
                            readTask.Wait();
                            ML.Usuario usuarioItem = new ML.Usuario();
                            usuarioItem = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Usuario>(readTask.Result.Object.ToString());
                            result.Object = usuarioItem;
                            result.Correct = true;
                        }
                        else
                        {
                            result.Correct = false;
                        }
                    }

                }
                catch(Exception ex)
                {
                    result.Correct = false;
                    result.Message = ex.Message;
                }

                if (result.Correct)
                {

                    usuario = (ML.Usuario)result.Object;
                    usuario.Rol.Roles = resultRol.Objects;

                    usuario.Direccion.Colonia.Municipio.Estado.Pais.Paises = resultPais.Objects;

                    ML.Result resulEstado = BL.Estado.GetByIdPais(usuario.Direccion.Colonia.Municipio.Estado.Pais.IdPais);
                    usuario.Direccion.Colonia.Municipio.Estado.Estados = resulEstado.Objects;

                    ML.Result resultMunicipio = BL.Municipio.GetByIdEstado(usuario.Direccion.Colonia.Municipio.Estado.IdEstado);
                    usuario.Direccion.Colonia.Municipio.Municipios = resultMunicipio.Objects;

                    ML.Result resultColonia = BL.Colonia.GetByIdMunicipio(usuario.Direccion.Colonia.Municipio.IdMunicipio);
                    usuario.Direccion.Colonia.Colonias = resultColonia.Objects;

                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al consultar al usuario seleccionado";
                }
                return View(usuario);
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Usuario usuario)
        {
            IFormFile image = Request.Form.Files["inputImagen"];


            if(image != null)
            {
                byte[] ImagenBytes = ConvertToBytes(image);

                usuario.Imagen = Convert.ToBase64String(ImagenBytes);
            }
               
            


            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(x => x.Errors);
                usuario.Rol = new ML.Rol();
                usuario.Direccion = new ML.Direccion();
                usuario.Direccion.Colonia = new ML.Colonia();
                usuario.Direccion.Colonia.Municipio = new ML.Municipio();
                usuario.Direccion.Colonia.Municipio.Estado = new ML.Estado();
                usuario.Direccion.Colonia.Municipio.Estado.Pais = new ML.Pais();

                ML.Result resultPais = BL.Pais.GetAll();
                ML.Result resultRol = BL.Rol.GetAll();

                usuario.Rol.Roles = resultRol.Objects;
                usuario.Direccion.Colonia.Municipio.Estado.Pais.Paises = resultPais.Objects;
                return View(usuario);

            }

            else
            {
                if (usuario.IdUsuario == 0)
                {
                    //HttpPostedFileBase FileBase = Request.Files["inputImagen"];  obtener un archivo en este caso de imagen


                    //if (FileBase.ContentLength > 0)
                    //{
                    //    usuario.Imagen = ConvertToBytes(FileBase);
                    //}

                    ML.Result result = new ML.Result();

PL/Views/Departamento/Form.cshtml
@model ML.Departamento
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Form</h2>

    

        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Departamento", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {

                <div class="row">
                    <div class="col-6">
                        <div class="form-group" style = "display: none;">
                        <div class="">

                            @Html.LabelFor(model => model.IdDepartamento, new { @class = "hidden" })

                            @Html.TextBoxFor(model => model.IdDepartamento, new { @class = "hidden form-control" })

                            @Html.ValidationMessageFor(model => model.IdDepartamento)

                        </div>

                    </div>

                    <div class="form-group">
                        <div class="">

                            @Html.LabelFor(model => model.Nombre)

                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "textNombre" })

                            @Html.ValidationMessageFor(model => model.Nombre)
                        </div>

                    </div>
                    </div>

                    <div class="col-3">
                         <div class="form-group">
                            <div class="">

                                @Html.LabelFor(model => model.Area.IdArea)
                                @*  @Html.TextBoxFor(model => model.Rol.IdRol, new { @class = "form-control" }) *@

                                @Html.DropDownListFor(model => model.Area.IdArea, new SelectList(Model.Area.Areas, "IdArea", "Nombre"), "Seleciona un Area", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Area.IdArea)

                            </div>
                        </div>
                    </div>
                </div>

                <div class="row p-2">
                    <div class="form-group">
                        <div class="col-md-12 d-flex justify-content-evenly p-2">


                            <input type="submit" value="Guardar" class="btn btn-success" />

                            @Html.ActionLink("Regresar", "GetAll", "Departamento", htmlAttributes: new { @class = "btn btn-danger" })

                        </div>
                    </div>
                </div>
                <div class="form-horizontal">
                    

                   
                   


                    

                </div>

            }

        </div>

    
</div>

PL/Views/Departamento/GetAll.cshtml
@model ML.Departamento;
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
        <h2>Usuarios</h2>
        <div class="row" >
            <div style="float:right">
               @Html.ActionLink("+", "Form", "Usuario", htmlAttributes: new { @class ="btn btn-success"})
            </div>
            
        </div>
        <hr />
        <div class="row">
            @*<div class="table-responsive">*@

                <table class="table ">
                    <thead>
                        <tr>
                            <!--<th>IdDepartamento</th>-->
                            <th>Nombre</th>
                       
                            @*<th>IdArea</th>*@
                            <th>NombreArea</th>
                          

                            <th>Editar</th>
                            <th>Eliminar</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (ML.Departamento departamento in Model.Departamentos)
                             {
                        <tr>
                            @*<td class="hidden">@usuario.IdUsuario</td>*@
                            <td>@departamento.Nombre</td>

                            @*<td class="hidden">@usuario.Rol.IdRol</td>*@
                            <td>@departamento.Area.Nombre</td>
                            
                       



                            <td class="text-center"><a class="btn btn-warning bi bi-pencil-square" href="@Url.Action("Form","Departamento", new { IdDepartamento = departamento.IdDepartamento})"></a></td>
                            <td class="text-center"><a class="btn btn-danger bi bi-trash3" href="@Url.Action("Delete","Departamento", new { IdDepartamento = departamento.IdDepartamento })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                        </tr>
                             }
                    </tbody>
                </table>

            @*</div>*@
        </div>
    </div>

PL/Views/Departamento/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Usuario", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>