PL/Controllers/DepartamentoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class DepartamentoController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = BL.Departamento.GetAll();
            ML.Departamento departamento = new ML.Departamento();

            if (result.Correct)
            {
                departamento.Departamentos = result.Objects;   
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta ";
            }


            return View(departamento);
        }

        [HttpGet]
        public ActionResult Form(int? IdDepartamento)
        {
            ML.Departamento departamento = new ML.Departamento();

            departamento.Area = new ML.Area();

            ML.Result resultArea = BL.Area.GetAll();

            if(IdDepartamento ==null)
            {
                departamento.Area.Areas = resultArea.Objects;
                return View(departamento);
            }
            else
            {
                ML.Result result = BL.Departamento.GetById(IdDepartamento.Value);

                if(result.Correct)
                {
                    departamento = (ML.Departamento)result.Object;
                    departamento.Area.Areas = resultArea.Objects;
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al buscar al departamento";
                }
                return View(departamento);

            }

            
        }

        [HttpPost]
        public ActionResult Form(ML.Departamento departamento)
        {
            if(departamento.IdDepartamento == 0)
            {
                ML.Result result = BL.Departamento.Add(departamento);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
                    
            }
            else
            {
                ML.Result result = BL.Departamento.Update(departamento);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }

            }
            return PartialView("Modal");
        }

        public ActionResult Delete(int IdDepartamento)
        {
            if (IdDepartamento > 0)
            {
                ML.Result result = BL.Departamento.Delete(IdDepartamento);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
                return PartialView("Modal");
        }
    }
}

PL/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class ProductoController : Controller
    {
        [HttpGet]
        public ActionResult GetAll()
        {
           
            ML.Result resultProveedores = BL.Proveedor.GetAll();
            ML.Producto producto = new ML.Producto();
            producto.Proveedor = new ML.Proveedor();
            ML.Result result = BL.Producto.GetAll(producto);
          

            if (result.Correct)
            {
                producto.Proveedor.Proveedores = resultProveedores.Objects;
                producto.Productos = result.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }

            return View(producto);
        }

        [HttpPost]
        public ActionResult GetAll(ML.Producto producto)
        {
            
            ML.Result result = BL.Producto.GetAll(producto);

            producto.Proveedor = new ML.Proveedor();
            ML.Result resultProveedores = BL.Proveedor.GetAll();


            if (result.Correct)
            {
                producto.Proveedor.Proveedores = resultProveedores.Objects;

                producto.Productos = result.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }

            return View(producto);
        }

        [HttpGet]
        public ActionResult Form(int? IdProducto)
        {
            ML.Producto producto = new ML.Producto();
            producto.Proveedor = new ML.Proveedor();
            producto.Departamento = new ML.Departamento();
            producto.Departamento.Area = new ML.Area();

            ML.Result resultProveedores = BL.Proveedor.GetAll();
            ML.Result resultArea = BL.Area.GetAll();

            if(IdProducto == null)
            {
                producto.Proveedor.Proveedores = resultProveedores.Objects;
                producto.Departamento.Area.Areas = resultArea.Objects;

                return View(producto);
            }
            else
            {
                ML.Result result = BL.Producto.GetById(IdProducto.Value);

                if (result.Correct)
                {
                    producto = (ML.Producto)result.Object;
                    producto.Proveedor.Proveedores = resultProveedores.Objects;
                    producto.Departamento.Area.Areas= resultArea.Objects;
                    ML.Result resultDepartaamento = BL.Departamento.GetByIdArea(producto.Departamento.Area.IdArea);
                    producto.Departamento.Departamentos = resultDepartaamento.Objects;

                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al consultar el producto seleccionado";
                }


                return View(producto);
            }

            
        }
        [HttpPost]
        public ActionResult Form(ML.Producto producto)
        {
            IFormFile image = Request.Form.Files["inputImagen"];

            if (image != null)
            {
                byte[] ImagenBytes = ConvertToBytes(image);

                producto.Imagen = Convert.ToBase64String(ImagenBytes);
            }

            if(producto.IdProducto == 0)
            {
                ML.Result result = BL.Producto.Add(producto);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            else
            {
                ML.Result result = BL.Producto.Update(producto);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }

            return PartialView("Modal");
        }

        public ActionResult Delete(int IdProducto)
        {
            if(IdProducto > 0)
            {
                ML.Result result = BL.Producto.Delete(IdProducto);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            return PartialView("Modal");
        }


        public JsonResult GetDepartamento(int IdArea)
        {
            var result = BL.Departamento.GetByIdArea(IdArea);

            return Json(result.Objects);
        }


        public static Byte[] ConvertToBytes(IFormFile imagen)
        {
            using var fileStream = imagen.OpenReadStream();

            byte[] bytes = new byte[fileStream.Length];
            fileStream.Read(bytes, 0, (int)fileStream.Length);

            return bytes;
        }
    }


}

PL/Views/Producto/Form.cshtml
@model ML.Producto
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Productos</h2>

    <div class="row">

        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Producto", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {

                <div class="row">
                    <div class="col-8">
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group" style = "display: none;">
                                    <div class="">

                                        @Html.LabelFor(model => model.IdProducto, new { @class = "hidden" })

                                        @Html.TextBoxFor(model => model.IdProducto, new { @class = "hidden form-control" })

                                        @Html.ValidationMessageFor(model => model.IdProducto)

                                    </div>

                                </div>

                                    <div class="form-group">
                                        <div class="">

                                            @Html.LabelFor(model => model.Nombre)

                                             <div class="input-group mb-3">
                                                <span class="input-group-text" id="basic-addon1"><i class="bi bi-card-text"></i></span>
                                                  @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "textNombre" })

                                                  @Html.ValidationMessageFor(model => model.Nombre)
                                            </div>

                                            
                                        </div>

                                    </div>
                            </div>

                            <div class="col-6">
                                <div class="form-group">
                                    <div class="">
                                        @Html.LabelFor(model => model.Proveedor.IdProveedor)

                                        <div class="input-group mb-3">
                                                <span class="input-group-text" id="basic-addon1"><i class="bi bi-shop-window"></i></span>
                                                    @Html.DropDownListFor(model => model.Proveedor.IdProveedor, new SelectList(Model.Proveedor.Proveedores, "IdProveedor", "Telefono"), "Slecione un proveedor", new { id = "ddlProveedor", @class = "form-control" })
                                                    @Html.ValidationMessageFor(model => model.Proveedor.IdProveedor)
                                            </div>

                                        

                                    </div>
                                </div>
                            </div>




                        </div>

                        <div class="row">
                            <div class="col-6">

                                <div class="form-group">
                                    <div class="">

                                        @Html.LabelFor(model => model.PrecioUnitario)
                                        <div class="input-group mb-3">
                                                <span class="input-group-text" id="basic-addon1"><i class="bi bi-cash"></i></span>
                                                  @Html.TextBoxFor(model => model.PrecioUnitario, new { @class = "form-control" })
                                                  @Html.ValidationMessageFor(model => model.PrecioUnitario)
                                         </div>

                                        

                                    </div>

                                </div>
                            </div>

                            <div class="col-6">
                                        <div class="form-group">
                                            <div class="">
                                                @Html.LabelFor(model => model.Departamento.Area.IdArea)
                                                 <div class="input-group mb-3">
                                                        <span class="input-group-text" id="basic-addon1"><i class="bi bi-collection"></i></span>
                                                          @Html.DropDownListFor(model => model.Departamento.Area.IdArea, new SelectList(Model.Departamento.Area.Areas, "IdArea", "Nombre"), "Slecione un Area", new { id = "ddlArea", @class = "form-control" })
                                                          @Html.ValidationMessageFor(model => model.Departamento.Area.IdArea)
                                                 </div>

                                               

                                            </div>
                                        </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <div class="">

                                        @Html.LabelFor(model => model.Stock)

                                        <div class="input-group mb-3">
                                                <span class="input-group-text" id="basic-addon1"><i class="bi bi-box-fill"></i></span>
                                                  @Html.TextBoxFor(model => model.Stock, new { @class = "form-control" })
                                                  @Html.ValidationMessageFor(model => model.Stock)
                                         </div>
                                        
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                 <div class="form-group">
                                    <div class="">
                                        @Html.LabelFor(model => model.Departamento)
                                        <div class="input-group mb-3">
                                                        <span class="input-group-text" id="basic-addon1"><i class="bi bi-collection"></i></span>
                                                                               @if (Model.Departamento.Departamentos == null)
                                                            {
                                                                @Html.DropDownListFor(model => model.Departamento.IdDepartamento, new SelectList(string.Empty, "Value", "Text"), "Selecciona un departamento", htmlAttributes: new { id = "ddlDepartamento", @class = "form-control" })
                                                            }
                                                            else
                                                            {
                                                                @Html.DropDownListFor(model => model.Departamento.IdDepartamento, new SelectList(Model.Departamento.Departamentos, "IdDepartamento", "Nombre"), "Selecione un departamento", new { id = "ddlDepartamento", @class = "form-control" })
                                                            }
                                                 </div>
                                       

                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <div class="" >

                                        @Html.LabelFor(model => model.Descripcion)


                                        <div class="input-group mb-3">
                                                <span class="input-group-text" id="basic-addon1"><i class="bi bi-card-text"></i></span>
                                                  @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control", @rows="3"})
                                                  @Html.ValidationMessageFor(model => model.Descripcion)
                                         </div>
                                        

                                    </div>
                                </div>
                            </div>
                        </div>



                    </div>



                    <div class="col-4">
                            <div class="form-group">

                            <div class="">
                                @Html.LabelFor(model => model.Imagen)
                                    <div class="input-group mb-3">
                                        <span class="input-group-text" id="basic-addon1"><i class="bi bi-card-image"></i></span>
                                     
                                        <input type="file" name="inputImagen" onchange="readURL(this);" class="input-group-text">
                                    </div>
                                
                                @if (Model.Imagen != null)
                                {
                                    <img id="ImagenPreview" src="data:image/jpeg;base64, @(Model.Imagen)" width="150" height="150" />
                                }
                                else
                                {
                                    <img id="ImagenPreview" src="~/productoSinImagen.png" style=" height: 150px; width: 150px; " />
                                }

                                @Html.ValidationMessageFor(model => model.Imagen)
                            </div>

                        </div>
                        @Html.HiddenFor(model => model.Imagen)

                    </div>


                </div>


                <div class="row p-2">

                    <div class="form-group p-2">
                        <div class="col-md-12 d-flex justify-content-evenly p-2">


                            <input type="submit" value="Guardar" class="btn btn-success" />

                            @Html.ActionLink("Regresar", "GetAll", "Departamento", htmlAttributes: new { @class = "btn btn-danger" })

                        </div>
                    </div>

                </div>



               

            }

        </div>

    </div>
</div>

@section Scripts
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript">

    
        $(document).ready(function () {
            $("#ddlArea").change(function () {
                $("#ddlDepartamento").empty();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetDepartamento")',
                    dataType: 'json',
                    data: { IdArea: $("#ddlArea").val() },
                    success: function (departamentos) {
                        $("#ddlDepartamento").append('<option value="0">' + 'Seleccione una opción' + '</option>');
                        $.each(departamentos, function (i, departamentos) {
                            $("#ddlDepartamento").append('<option value="'
                                + departamentos.idDepartamento + '">'
                                + departamentos.nombre + '</option>');
                        });
                    },
                    error: function (ex) {
                        alert('Failed.' + ex);
                    }
                });
            });

          });

           


    </script>

    <script type="text/javascript">

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#ImagenPreview').attr('src', e.target.result);

            };

            reader.readAsDataURL(input.files[0]);

        }
    }
</script>

}

PL/Views/Producto/GetAll.cshtml
@model ML.Producto
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Productos</h2>


    <div class="row">

         <div class="col-11">

             <div class="row">
                    <div>
                            @using (Html.BeginForm("GetAll", "Producto", FormMethod.Post, new { enctype ="multipart/form-data"}))
                             {
                             <div class="row">

                                 <div class="col-4">
                                                <div class="">
                                                    @Html.DropDownListFor(model => model.Proveedor.IdProveedor, new SelectList(Model.Proveedor.Proveedores, "IdProveedor", "Telefono"), "Slecione un proveedor", new { id = "ddlProveedor", @class = "form-control" })
                                                </div>
                                 </div>

                                 <div class="col-4" >
                                    @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @placeholder= "Nombre" } )
                                </div>

                                <div class="col-md-3">
                                     <input type="submit" value="Buscar" class="btn btn-info" />
                                </div>
                              </div>

                             }
                    </div>

             </div>

         </div>


          <div class="col-1">
              <div>
                    @Html.ActionLink("+", "Form", "Producto", htmlAttributes: new { @class ="btn btn-success"})
              </div>

         </div>


    </div>

    



    <hr />
    <div class="row">
        @*<div class="table-responsive">*@

        <table class="table" id="tablaProducto">
            <thead>
                <tr>
                    <!--<th>IdProducto</th>-->
                    <th>Nombre</th>
                    <th>PrecioUnitario</th>
                    <th>Stock</th>
                    @*<th>IdProveedor</th>*@
                    <th>Telefono</th>
                    @*<th>IdDepartamento</th>*@
                    <th>NombreDepartamento</th>
                    @*<th>IdArea</th>*@

                    <th>NombreArea</th>
                    <th>Descripcion</th>
                    <th>Imagen</th>



                    <th>Editar</th>
                    <th>Eliminar</th>
                </tr>
            </thead>

            <tbody>
                @foreach (ML.Producto producto in Model.Productos)
                             {
                <tr>
                    @*<td class="hidden">@producto.IdProducto</td>*@
                    <td>@producto.Nombre </td>
                    <td>@producto.PrecioUnitario</td>
                    <td>@producto.Stock</td>
                    <td>@producto.Proveedor.Telefono</td>

                    <td>@producto.Departamento.Nombre</td>
                    <td>@producto.Departamento.Area.Nombre</td>
                    <td>@producto.Descripcion</td>
                    @*<td class="hidden">@usuario.Rol.IdRol</td>*@
                    
                    @if (producto.Imagen != null)
                            {
                    <td><img src="data:image/jpeg;base64, @producto.Imagen" style=" height: 150px; width: 150px;" /></td>
                            }
                            else
                            {
                    <td><img src="~/productoSinImagen.png" style=" height: 150px; width: 160px;" alt="Imagen usuario"></td>
                            }


                    

                    <td class="text-center"><a class="btn btn-warning bi bi-pencil-square" href="@Url.Action("Form","Producto", new { IdProducto = producto.IdProducto})"></a></td>
                    <td class="text-center"><a class="btn btn-danger bi bi-trash3" href="@Url.Action("Delete","Producto", new { IdProducto = producto.IdProducto })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                </tr>
                             }
            </tbody>
        </table>

        @*</div>*@
    </div>
</div>



@section Scripts
{

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

<script>
    $(document).ready(function () {
        $('#tablaProducto').DataTable({
            searching: false,
            "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
            autoWidth: false,
            columnDefs: [
                {
                    targets: ['_all'],
                    className: 'mdc-data-table__cell',
                },
            ],
            language: {
                url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
            },
         });
    });
</script>

}

PL/Views/Producto/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Producto", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>